sudo: false
language: python
python:
  - "2.7"
script:
  - mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: site
  on:
    branch: master

env:
  global:
    - GH_COMMIT_AUTHOR="Travis CI"
    - GH_COMMIT_EMAIL=travisci@travisci.org
    - ENCRYPTION_LABEL=ddaacfe268bd

notifications:
  email:
    - raj.muthukkannan@wolterskluwer.com
